<?php
/**
 *
 * This file is part of the phpBB Forum Software package.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
    exit;
}

if (empty($lang) || !is_array($lang))
{
    $lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
    'TRANSLATION_INFO'	=> '',
    'DIRECTION'			=> 'ltr',
    'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
    'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
    'USER_LANG'			=> 'lv',

    // You can define different rules for the determination of plural forms here.
    // See http://wiki.phpbb.com/Plural_Rules for more information
    // or ask the translation manager for help.
    'PLURAL_RULE'		=> 1,

    '1_DAY'			=> '1 diena',
    '1_MONTH'		=> '1 mēnesis',
    '1_YEAR'		=> '1 gads',
    '2_WEEKS'		=> '2 nedēļas',
    '3_MONTHS'		=> '3 mēneši',
    '6_MONTHS'		=> '6 mēneši',
    '7_DAYS'		=> '7 dienas',

    'ACCOUNT_ALREADY_ACTIVATED'		=> 'Jūsu konts jau ir aktivizēts.',
    'ACCOUNT_DEACTIVATED'			=> 'Jūsu konts ir ticis manuāli deaktivizēts un to var aktvizēt tikai administrators.',
    'ACCOUNT_NOT_ACTIVATED'			=> 'Jūsu konts vēl nav ticis aktivizēts.',
    'ACP'							=> 'Administrācijas panelis',
    'ACP_SHORT'						=> 'ACP',
    'ACTIVE'						=> 'aktīvs',
    'ACTIVE_ERROR'					=> 'Norādītais konta vārds pašlaik ir neaktīvs. Ja Jums ir problēmas ar konta aktivizāciju, lūdzu sazinieties ar foruma administratoru.',
    'ADMINISTRATOR'					=> 'Administrators',
    'ADMINISTRATORS'				=> 'Administratori',
    'AGE'							=> 'Vecums',
    'AIM'							=> 'AIM',
    'AJAX_ERROR_TITLE'				=> 'AJAX kļūda',
    'AJAX_ERROR_TEXT'				=> 'Kaut kas atgadījās, apstrādājot AJAX pieprasījumu.',
    'AJAX_ERROR_TEXT_ABORT'			=> 'Lietotāja pārtraukts pieprasījums.',
    'AJAX_ERROR_TEXT_TIMEOUT'		=> 'Pieprasījuma laiks ir beidzies; mēģiniet vēlreiz.',
    'AJAX_ERROR_TEXT_PARSERERROR'	=> 'Kaut kas atgadījās, serveris atgrieza kļūdainu atbildi.',
    'ALLOWED'						=> 'Atļauts',
    'ALL_FILES'						=> 'Visi faili',
    'ALL_FORUMS'					=> 'Visi forumi',
    'ALL_MESSAGES'					=> 'Visas ziņas',
    'ALL_POSTS'						=> 'Visi ziņojumi',
    'ALL_TIMES'						=> 'Visi laiki ir %1$s %2$s',
    'ALL_TOPICS'					=> 'Visi temati',
    'AND'							=> 'Un',
    'ARE_WATCHING_FORUM'			=> 'Jūs saņemsiet atgādinājumu par jauniem ziņojumiem šajā forumā.',
    'ARE_WATCHING_TOPIC'			=> 'Jūs saņemsiet atgādinājumu par jauniem ziņojumiem šajā tēmā.',
    'ASCENDING'						=> 'Augoša',
    'ATTACHMENTS'					=> 'Pievienotie faili',
    'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Attēls, kuru mēģinājāt pievienot ir nederīgs.',
    'AUTHOR'						=> 'Autors',
    'AUTH_NO_PROFILE_CREATED'		=> 'Lietotāja konta izveidošana bija neveiksmīga.',
    'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'Nederīgs datu bāzes ieraksts.',
    'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'Nederīgs ar pakalpojuma tips Autorizācijas protokolam.',
    'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'Nav Autorizācijas protokolam pakalpojumu',
    'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
    'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
    'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
    'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'Autorizācijas token protokols nav saglabāts.',
	//Baigi grūti tulkoja token https://en.wikipedia.org/wiki/Token_ring
    'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'Autorizācijas token nepareizi saglabāts.',
    'AVATAR_DISALLOWED_CONTENT'		=> 'Augšuplāde tika atcelta, jo pielikums tika uztverts kā potenciāli bīstams. .',
    'AVATAR_DISALLOWED_EXTENSION'	=> 'Šis fails nevar tikt attēlots, jo tā paplašinājums <strong>%s</strong> nav atļauts.',
    'AVATAR_EMPTY_REMOTE_DATA'		=> 'Šis avatars nevar tikt ielādēts, jo iespējams satur nepariezus datus vai ir bojāts.',
    'AVATAR_EMPTY_FILEUPLOAD'		=> 'Augšuplādētā avatara fails ir tukšs.',
    'AVATAR_INVALID_FILENAME'		=> '%s ir nederīgs faila nosaukums.',
    'AVATAR_NOT_UPLOADED'			=> 'Avataru neizdevās augšuplādēt.',
    'AVATAR_NO_SIZE'				=> 'Neizdevās noteikt avatara platumu un augstumu. Lūdzu, norādiet tos paši.',
    'AVATAR_PARTIAL_UPLOAD'			=> 'Norādītais fails tika tikai daļēji augšuplādēts.',
    'AVATAR_PHP_SIZE_NA'			=> 'Avatar faila izmērs ir par lielu.<br />Neizdevās noteikt maksimālo php.ini noteikto izmēru.',
    'AVATAR_PHP_SIZE_OVERRUN'		=> 'Avatar faila izmērs ir par lielu. Maksimālais faila izmērs ir %1$d %2$s.<br />Šis ierobežojums ir norādīts php.ini un nevar tikt pārsniegts.',
    'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'Norādīto avatar nevarēja augšupielādēt, jo iestājās pieprasījuma taimauts',
    'AVATAR_URL_INVALID'			=> 'Nepareiza URL adrese.',
    'AVATAR_URL_NOT_FOUND'			=> 'Fails netika atrasts.',
    'AVATAR_WRONG_FILESIZE'			=> 'Avatara faila izmēriem jābūt robežās no 0 līdz %1d %2s.',
    'AVATAR_WRONG_SIZE'				=> 'Avatara izmēri ir %5$d pikseļi platums un %6$d pikseļi augstums. Avataram jābūt vismaz %1$d pikseļu platam un %2$d pikseļu augstam, bet tas nedrīkst pārsniegt %3$d pikseļu platumu un %4$d pikseļu augstumu.',

    'BACK_TO_TOP'			=> 'Uz augšu',
    'BACK_TO_PREV'			=> 'Atpakaļ uz iepriekšējo lapu',
    'BAN_TRIGGERED_BY_EMAIL'=> 'Jūsu e-pasta adrese ir banota.',
    'BAN_TRIGGERED_BY_IP'	=> 'Jūsu IP adrese ir banota.',
    'BAN_TRIGGERED_BY_USER'	=> 'Jūsu lietotājvārds ir banots',
    'BBCODE_GUIDE'			=> 'BBCode palīdzība',
    'BCC'					=> 'BCC',
    'BIRTHDAYS'				=> 'Dzimšanas dienas',
    'BOARD_BAN_PERM'		=> 'Jums ir uzlikts <strong>permanent</strong> bans.<br /><br />Lai saņemtu sīkāku informāciju, lūgums %2$ssazināties ar konferences Administrātoru%3$s.',
    'BOARD_BAN_REASON'		=> 'Bana iemesls: <strong>%s</strong>',
    'BOARD_BAN_TIME'		=> 'Jums ir uzlikts bans līdz <strong>%1$s</strong>.<br /><br />Lai saņemtu sīkāku informāciju, lūgums %2$ssazināties ar konferences Administrātoru%3$s.',
    'BOARD_DISABLE'			=> 'Atvainojamies, forums šobrīd nav pieejams.',
    'BOARD_DISABLED'		=> 'Šobrīd forums ir slēgts.',
    'BOARD_UNAVAILABLE'		=> 'Atvainojamies, bet šobrīd forums nav pieejams. Lūdzu, mēģiniet pēc dažām minūtēm.',
    'BROWSING_FORUM'		=> 'Lietotāji, kuri atrodas šajā forumā: %1$s',
    'BROWSING_FORUM_GUESTS'	=> array(
        1	=> 'Lietotāji, kuri atrodas šajā forumā: %1$s un %2$d viesis',
        2	=> 'Lietotāji, kuri atrodas šajā forumā: %1$s un %2$d viesi',
    ),
    'BUTTON_EDIT'			=> 'Labot',
    'BUTTON_FORUM_LOCKED'	=> 'Slēgts',
    'BUTTON_NEW_TOPIC'		=> 'Jauns raksts',
    'BUTTON_PM'				=> 'PZ',
    'BUTTON_PM_FORWARD'		=> 'Pārsūtīt',
    'BUTTON_PM_NEW'			=> 'Jauna PZ',
    'BUTTON_PM_REPLY'		=> 'Sūtīt atbildi',
    'BUTTON_PM_REPLY_ALL'	=> 'Atbildēt visiem',
    'BUTTON_POST_REPLY'		=> 'Atbildēt',
    'BUTTON_QUOTE'			=> 'Iekļaut',
    'BUTTON_TOPIC_LOCKED'	=> 'Slēgts',
    'BYTES'					=> 'Baiti',
    'BYTES_SHORT'			=> 'B',

    'CANCEL'				=> 'Atcelt',
    'CHANGE'				=> 'Mainīt',
    'CHANGE_FONT_SIZE'		=> 'Mainīt fonta izmēru',
    'CHANGING_PREFERENCES'	=> 'Mainīt foruma iestatījumus',
    'CHANGING_PROFILE'		=> 'Mainīt konta iestatījumus',
    'CHARACTERS'			=> array(
        1	=> '%d simbols',
        2	=> '%d simboli',
    ),
    'COLLAPSE_VIEW'			=> 'Aizvērt skatījumu',
    'CLOSE_WINDOW'			=> 'Aizvērt logu',
    'COLOUR_SWATCH'			=> 'Krāsu pārslēgšana',
    'COLON'					=> ':',
    'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
    'CONFIRM'				=> 'Apstiprināt',
    'CONFIRM_CODE'			=> 'Drošības kods',
    'CONFIRM_CODE_EXPLAIN'	=> 'Lūdzu ievadiet drošības kodu. Burtu izmēram nav nozīmes un kods nesatur nulles.',
    'CONFIRM_CODE_WRONG'	=> 'Drošības kods ievadīts nepareizi',
    'CONFIRM_OPERATION'		=> 'Vai tiešām vēlaties izpildīt šo operāciju?',
    'CONFIRM_AVATAR_DELETE' => 'Tiešām vēlies izdzēst avataru?',
    'CONGRATULATIONS'		=> 'Apsveicam',
    'CONNECTION_FAILED'		=> 'Pieslēgšanās kļūda.',
    'CONNECTION_SUCCESS'	=> 'Pieslēgšanās veiksmīga!',
    'CONTACT'				=> 'Kontakts',
    'CONTACT_USER'			=> 'Rakstīt %s',
    'CONTACT_US'			=> 'Kontakti',
    'COOKIES_DELETED'		=> 'Foruma cepumi ir veiksmīgi izdzēsti.',
    'CURRENT_TIME'			=> 'Šobrīd ir %s',

    'DAY'					=> 'Diena',
    'DAYS'					=> 'Dienas',
    'DELETE'				=> 'Dzēst',
    'DELETE_ALL'			=> 'Dzēst visas',
    'DELETE_COOKIES'		=> 'Dzēst visas foruma sīkdatnes (cookies)',
    'DELETE_MARKED'			=> 'Dzēst iezīmētās',
    'DELETE_POST'			=> 'Dzēst ziņojumu',
    'DELIMITER'				=> 'Atdalītājs',
    'DESCENDING'			=> 'Dilstoša',
    'DISABLED'				=> 'Aizliegts',
    'DISPLAY'				=> 'Attēlot',
    'DISPLAY_GUESTS'		=> 'Rādīt viesus',
    'DISPLAY_MESSAGES'		=> 'Rādīt ziņas',
    'DISPLAY_POSTS'			=> 'Attēlot ziņojumus sākot ar pirmspēdējo',
    'DISPLAY_TOPICS'		=> 'Attēlot tēmas sākot ar iepriekšējo',
    'DOWNLOADED'			=> 'Lejuplādētie',
    'DOWNLOADING_FILE'		=> 'Lejuplādē failu',
    'DOWNLOAD_COUNTS'		=> array(
        0	=> 'Pagaidām nav lejuplādēts',
        1	=> 'Lejuplādēts %d reizi',
        2	=> 'Lejuplādēts %d reizes',
    ),

    'EDIT_POST'							=> 'Labot ziņojumu',
    'ELLIPSIS'							=>	'…',
    'EMAIL'								=> 'E-pasts', // Short form for EMAIL_ADDRESS
    'EMAIL_ADDRESS'						=> 'E-pasta adrese',
    'EMAIL_INVALID_EMAIL'				=> 'Norādīta nepareiza e-pasta adrese.',
    'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Sūtot e-pastu, radās problēmas <strong>Rinda %1$s</strong>. Atbilde: %2$s.',
    'EMPTY_SUBJECT'						=> 'Nav norādīts virsraksts.',
    'EMPTY_MESSAGE_SUBJECT'				=> 'Norādiet tēmu, sastādot jaunu ziņu.',
    'ENABLED'							=> 'Iespējots',
    'ENCLOSURE'							=> 'Pielikums',
    'ENTER_USERNAME'					=> 'Ievadiet lietotājvārdu',
    'ERR_CHANGING_DIRECTORY'			=> 'Nevar mainīt mapi.',
    'ERR_CONNECTING_SERVER'				=> 'Kļūda pieslēdzoties serverim.',
    'ERR_JAB_AUTH'						=> 'Nav iespējams autorizēties ar Jabber serveri.',
    'ERR_JAB_CONNECT'					=> 'Nav savienojuma ar Jabber serveri.',
    'ERR_UNABLE_TO_LOGIN'				=> 'Lietotājvārds vai parole nav pareiza.',
    'ERR_UNWATCHING'					=> 'Radās kļūda, mēģinot atcelt pierakstīšanos.',
    'ERR_WATCHING'						=> 'Pierakstoties radās kļūda.',
    'ERR_WRONG_PATH_TO_PHPBB'			=> 'phpBB norādītais ceļš ir nederīgs.',
    'ERROR'									=> 'Kļūda',
    'EXPAND_VIEW'						=> 'Izvērst skatu',
    'EXTENSION'							=> 'Paplašinājums',
    'EXTENSION_DISABLED'				=> 'Paplašinājums  <strong>%s</strong> ir atslēgts.',
    'EXTENSION_DISABLED_AFTER_POSTING'	=> 'Paplašinājums <strong>%s</strong> ir atslēgts un nevar tikt attēlots.',
    'EXTENSION_DOES_NOT_EXIST'			=> 'Paplašinājums <strong>%s</strong> neeksistē.',

    'FACEBOOK'				=> 'Facebook',
    'FAQ'					=> 'BUJ',
    'FAQ_EXPLAIN'			=> 'Bieži uzdotie jautājumi',
    'FILENAME'				=> 'Datnes nosaukums',
    'FILESIZE'				=> 'Datnes izmērs',
    'FILEDATE'				=> 'Izveidošanas datums',
    'FILE_COMMENT'			=> 'Datnes komentārs',
    'FILE_CONTENT_ERR'		=> 'Nevar nolasīt datnes saturu: %s',
    'FILE_JSON_DECODE_ERR'	=> 'Kļūda atkodējot json datni: %s',
    'FILE_NOT_FOUND'		=> 'Pieprasītā datne nav atrasta: %s',
    'FIND_USERNAME'			=> 'Atrast lietotāju',
    'FOLDER'				=> 'Mape',
    'FORGOT_PASS'			=> 'Aizmirsu paroli',
    'FORM_INVALID'			=> 'Nosūtītie dati nav derīgi. Mēģiniet vēlreiz.',
    'FORUM'					=> 'Forums',
    'FORUMS'				=> 'Forumi',
    'FORUMS_MARKED'			=> 'Forumi atzīmēti kā lasīti.',
    'FORUM_CAT'				=> 'Foruma kategorija',
    'FORUM_INDEX'			=> 'Sākums',
    'FORUM_LINK'			=> 'Foruma adrese',
    'FORUM_LOCATION'		=> 'Foruma atrašanās vieta',
    'FORUM_LOCKED'			=> 'Forums slēgts',
    'FORUM_RULES'			=> 'Foruma noteikumi',
    'FORUM_RULES_LINK'		=> 'Klikšķini šeit, lai atvērtu foruma noteikumus',
    'FROM'					=> 'no',
    'FSOCK_DISABLED'		=> 'Operāciju nevarēja pabeigt, jo <var>fsockopen ()</var> funkcija ir atspējota vai serveris nav atrodams.',
    'FSOCK_TIMEOUT'			=> 'Lasīšanas laikā radās tīkla straumes taimauts.',

    'FTP_FSOCK_HOST'				=> 'FTP hosts',
    'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP serveris savienojumam ar saitu.',
    'FTP_FSOCK_PASSWORD'			=> 'FTP parole',
    'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'FTP lietotāja parole.',
    'FTP_FSOCK_PORT'				=> 'FTP ports',
    'FTP_FSOCK_PORT_EXPLAIN'		=> 'Ports savienojumam ar serveri.',
    'FTP_FSOCK_ROOT_PATH'			=> 'Ceļš uz phpBB',
    'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Ceļš no no saknes līdz jūsu phpBB forumam.',
    'FTP_FSOCK_TIMEOUT'				=> 'FTP taimauts',
    'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'Laika posms, sekundēs, ko šī sistēma gaidīs atbildi no servera.',
    'FTP_FSOCK_USERNAME'			=> 'FTP lietotājs',
    'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Lietotāja vārds lai pieslēgtos serverim.',

    'FTP_HOST'					=> 'FTP hosts',
    'FTP_HOST_EXPLAIN'			=> 'FTP serveris savienojumam ar saitu.',
    'FTP_PASSWORD'				=> 'FTP parole',
    'FTP_PASSWORD_EXPLAIN'		=> 'Parole FTP serverim.',
    'FTP_PORT'					=> 'FTP ports',
    'FTP_PORT_EXPLAIN'			=> 'Ports savienojumam ar serveri.',
    'FTP_ROOT_PATH'				=> 'Ceļš uz phpBB',
    'FTP_ROOT_PATH_EXPLAIN'		=> 'Ceļš uz mapi kurā atrodas phpBB.',
    'FTP_TIMEOUT'				=> 'FTP taimauts',
	'FTP_TIMEOUT_EXPLAIN'		=> 'Laiks sekundēs, cik ilgi sistēma gaidīs atbildi no FTP servera.',
    'FTP_USERNAME'				=> 'FTP lietotājvārds',
    'FTP_USERNAME_EXPLAIN'		=> 'Lietotājvārds savienojumam ar FTP serveri.',

    'GENERAL_ERROR'				=> 'Kļūda',
    'GB'						=> 'GB',
    'GIB'						=> 'GiB',
    'GO'						=> 'Pāriet',
    'GOOGLEPLUS'				=> 'Google+',
    'GOTO_FIRST_POST'			=> 'Iet uz pirmo ierakstu',
    'GOTO_LAST_POST'			=> 'Iet uz pēdējo ierakstu',
    'GOTO_PAGE'					=> 'Iet uz lapu',
    'GROUP'						=> 'Grupa',
    'GROUPS'					=> 'Grupas',
    'GROUP_ERR_TYPE'			=> 'Izvēlēts neatbilstošs grupas tips.',
    'GROUP_ERR_USERNAME'		=> 'Nav norādīts grupas nosaukums.',
    'GROUP_ERR_USER_LONG'		=> 'Grupas nosaukums nevar pārsniegt 60 zīmes. Norādītais nosaukums ir par garu.',
    'GUEST'						=> 'Viesis',
    'GUEST_USERS_ONLINE'		=> array(
        1	=> '%d viesis online',
        2	=> '%d viesi online',
    ),
    'GUEST_USERS_TOTAL'			=> array(
        1	=> '%d viesis',
        2	=> '%d viesi',
    ),
    'G_ADMINISTRATORS'			=> 'Administratori',
    'G_BOTS'					=> 'Boti',
    'G_GUESTS'					=> 'Viesi',
    'G_REGISTERED'				=> 'Reģistrētie lietotāji',
    'G_REGISTERED_COPPA'		=> 'Reģistrētie COPPA lietotāji',
	//Children's Online Privacy Protection Act of 1998
    'G_GLOBAL_MODERATORS'		=> 'Virsmoderatori',
    'G_NEWLY_REGISTERED'		=> 'Jaunie lietotāji',

    'HIDDEN_USERS_ONLINE'		=> array(
        1	=> '%d slēpts lietotājs',
        2	=> '%d slēpti lietotāji',
    ),
    'HIDDEN_USERS_TOTAL'		=> array(
        1	=> '%d slēpts',
        2	=> '%d slēpti',
    ),
    'HIDE_GUESTS'					=> 'Paslēpt viesus',
    'HIDE_ME'						=> 'Slēpt mani šajā sesijā',
    'HOURS'							=> 'Stundas',
    'HOME'							=> 'Sākums',

    'ICQ'						=> 'ICQ',
    'IF'						=> 'Ja',
    'IMAGE'						=> 'Attēls',
    'IMAGE_FILETYPE_INVALID'	=> 'Attēla fails ar tipu %d mime tipam %s netiek atbalstīts.',
    'IMAGE_FILETYPE_MISMATCH'	=> 'Attēla tipa nesakritība: gaidāmais paplašinājums %1$s saņemtā %2$s vietā.',
    'IN'						=> 'forumā',
    'INDEX'						=> 'Satura lapa',
    'INFORMATION'				=> 'Informācija',
    'INSECURE_REDIRECT'			=> 'Mēģinājums novirzīt uz potenciāli nedrošu url.',
    'INTERESTS'					=> 'Intereses',
    'INVALID_DIGEST_CHALLENGE'	=> 'Nepareizs autentifikācijas pieprasījums.',
    'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> iespējams ir nepareiza e-pasta adrese?',
    'INVALID_PLURAL_RULE'		=> 'The chosen plural rule is invalid. Valid values are integers between 0 and 15.',
    'IP'						=> 'IP',
    'IP_BLACKLISTED'			=> 'Jūsu IP %1$s adrese ir bloķēta jo atrodas melnajā sarakstā. Lai saņemtu sīkāku informāciju apmeklējiet <a href="%2$s">%2$s</a>.',

    'JABBER'				=> 'Jabber',
    'JOINED'				=> 'Pievienojies',
    'JUMP_PAGE'				=> 'Ievadiet lapas numuru uz kuru vēlaties pāriet',
    'JUMP_TO'				=> 'Pāriet uz',
    'JUMP_TO_PAGE'			=> 'Pārietu uz lapu…',
    'JUMP_TO_PAGE_CLICK'	=> 'Uzspiediet, lai pārietu uz lapu…',

    'KB'					=> 'KB',
    'KIB'					=> 'KiB',

    'LAST_POST'							=> 'Pēdējais ieraksts',
    'LAST_UPDATED'						=> 'Pēdējo reizi atjaunots',
    'LAST_VISIT'						=> 'Pēdējais apmeklējums',
    'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP paplašinājums nav pieejams.',
    'LDAP_NO_SERVER_CONNECTION'			=> 'Nav savienojuma ar LDAP serveri.',
    'LDAP_SEARCH_FAILED'				=> 'Kļūda mekējot LDAP direktoriju.',
    'LEGEND'							=> 'Leģenda',
    'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Dzīvā meklēšana nav atļauta.',
    'LOADING'							=> 'Lādējas',
    'LOCATION'							=> 'Atrašanās vieta',
    'LOCK_POST'							=> 'Bloķēt rakstu',
    'LOCK_POST_EXPLAIN'					=> 'Novērstu rediģēšanu',
    'LOCK_TOPIC'						=> 'Bloķēt tēmu',
    'LOGIN'								=> 'Pieslēgties',
    'LOGIN_CHECK_PM'					=> 'Pieslēdzieties, lai pārbaudītu privātos ziņojumus.',
    'LOGIN_CONFIRMATION'				=> 'Pieslēgšanās apstiprinājums',
    'LOGIN_CONFIRM_EXPLAIN'				=> 'Lai pasargātu lietotāja kontu no paroles piemeklēšanas, ir nepieciešams ievadīt apstiprinājuma kodu, pēc maksimāli atļauto neveiksmīgu ienākšanas mēģinājumu pārsniegšanas. Kods redzams attēlā zemāk. Ievadiet kodu tieši tā, kā redzams attēlā. Ja kods nav redzams, sazinaties ar %sadministrāciju%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'Jūs esat pārsniedzis maksimāli atļauto ielogošanās mēģinājumu skaitu. Tagad jums nepieciešams papildus lietotājvārda un paroles ievadīšanai, ievadīt arī drošības kodu, kurš redzams uz attēla zemāk.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Jūs neesat ticis identificēts Apache.',
    'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'Neeksistējošs Autorizācijas serviss.',
	'LOGIN_ERROR_PASSWORD'				=> 'Jūs esat ievadījuši nepareizu paroli. Pārbaudiet to un mēģiniet vēlreiz. Ja tomēr nespējat ielogoties, lūdzu sazinaties ar %sadministrāciju%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'Pie forumu atjaunošanas nav izdevies konvertēt jūsu paroli. Jūs varat %spieprasīt jaunu paroli%s. Ja jums neizdodas novērst problēmas, sazinaties ar %sadministrāciju%s.',
	'LOGIN_ERROR_USERNAME'				=> 'Jūs esat ievadījuši nepareizu paroli. Pārbaudiet to un mēģiniet vēlreiz. Ja tomēr nespējat ielogoties, lūdzu sazinaties ar %sadministrāciju%s.',
	'LOGIN_FORUM'						=> 'Lai apskatītu vai pievienotu ziņas šajā forumā, ir nepieciešams ievadīt paroli.',
	'LOGIN_INFO'						=> 'Lai ienāktu jums ir nepieciešams reģistrēties. Reģistrācija aizņem tikai dažus mirkļus un sniedz lielākas forumu izmantošanas priekšrocības. Administrācija, iespējams, ir sniegusi lielākas privilēģijas reģistrētiem lietotājiem. Pirms reģistrējaties, jums nepieciešams iepazīties ar noteikumiem. Atceraties, ka atrašanās forumos, nozīmē to, ka esat piekrituši visiem noteikumiem.',
	'LOGIN_VIEWFORUM'					=> 'Lai apskatītu šo forumu jums ir nepieciešams reģistrēties un ielogoties.',
	'LOGIN_EXPLAIN_EDIT'				=> 'Lai labotu ziņas šajā forumā jums ir nepieciešams reģistrēties un ielogoties.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'Lai apskatītu forumā esošo apmeklētāju sarakstu jums ir nepieciešams reģistrēties un ielogoties.',
    'LOGIN_REQUIRED'					=> 'Jums jāautorizējas, lai veiktu šo darbību.',
	'LOGOUT'							=> 'Iziet',
    'LOGOUT_USER'						=> 'Iziet [ %s ]',
    'LOG_ME_IN'							=> 'Atcerēties mani',

    'MAIN'					=> 'Galvenā',
    'MARK'					=> 'Iezīmēt',
    'MARK_ALL'				=> 'Iezīmēt visu',
    'MARK_ALL_READ'			=> 'Atzīmēt visu kā lasītu',
    'MARK_FORUMS_READ'		=> 'Atzīmēt kā lasītus',
    'MARK_READ'				=> 'Atzīmēt kā lasītu',
    'MARK_SUBFORUMS_READ'	=> 'Atzīmēt apakšforumus kā lasītus',
    'MB'					=> 'MB',
    'MIB'					=> 'MiB',
    'MCP'					=> 'Moderatora kontrolpanelis',
    'MCP_SHORT'				=> 'MCP',
    'MEMBERLIST'			=> 'Lietotāji',
    'MEMBERLIST_EXPLAIN'	=> 'Skatīt lietotāju sarakstu',
    'MERGE'					=> 'Apvienot',
    'MERGE_POSTS'			=> 'Pārvietot rakstus',
    'MERGE_TOPIC'			=> 'Apvienot tēmas',
    'MESSAGE'				=> 'Vēstule',
    'MESSAGES'				=> 'Vēstules',
    'MESSAGES_COUNT'		=> array(
        1	=> '%d vēstule',
        2	=> '%d vēstules',
    ),
    'MESSAGE_BODY'			=> 'Ziņojuma pamatteksts',
    'MINUTES'				=> 'Minūtes',
    'MODERATE'				=> 'Moderēt',
    'MODERATOR'				=> 'Moderators',
    'MODERATORS'			=> 'Moderatori',
    'MODULE_NOT_ACCESS'		=> 'Modulis nav pieejams',
    'MODULE_NOT_FIND'		=> 'Nevar atrast moduli %s',
    'MODULE_FILE_INCORRECT_CLASS'	=> 'Moduļa fails %s satur nekorektu klasi [%s]',
    'MONTH'					=> 'Mēnesis',
    'MOVE'					=> 'Pārvietot',

    'NA'						=> 'N/A',
    'NEWEST_USER'				=> 'Mūsu jaunākais biedrs: <strong>%s</strong>',
    'NEW_MESSAGE'				=> 'Jauna ziņa',
    'NEW_MESSAGES'				=> 'Jaunas ziņas',
    'NEW_POST'					=> 'Jauns ziņojums',	// Not used anymore
    'NEW_POSTS'					=> 'Jauni ziņojumsi',	// Not used anymore
    'NEXT'						=> 'Nākošais',		// Used in pagination
    'NEXT_STEP'					=> 'Nākošais',
    'NEVER'						=> 'Nekad',
    'NO'						=> 'Nē',
    'NO_NOTIFICATIONS'			=> 'Jums nav paziņojumi',
    'NOT_ALLOWED_MANAGE_GROUP'	=> 'Jums nav tiesību vadīt šo grupu.',
    'NOT_AUTHORISED'			=> 'Jums nav tiesību lai piekļūtu šai foruma daļai.',
    'NOT_WATCHING_FORUM'		=> 'You are no longer subscribed to updates on this forum.',
    'NOT_WATCHING_TOPIC'		=> 'You are no longer subscribed to this topic.',
    'NOTIFICATIONS'				=> 'Paziņojumi',
    // This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
    // %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
    // Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
    // Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
    // Examples:
    // A replied...
    // A and B replied...
    // A, B and C replied...
    // A, B, C and 2 others replied...
    // A, B, C and others replied...
    'NOTIFICATION_BOOKMARK'				=> array(
        1	=> '<strong>Atbilde</strong> no %1$s ar grāmatzīmi atzīmētajā tēmā:',
    ),
    'NOTIFICATION_FORUM'				=> '<em>Forums:</em> %1$s',
    'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Grupas pieprasījums</strong> no %1$s pievienoties grupai %2$s.',
    'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Grupas pieprasījums apstiprināts</strong> pievienoties grupai %1$s.',
    'NOTIFICATION_PM'					=> '<strong>Privāta Ziņa</strong> no %1$s:',
    'NOTIFICATION_POST'					=> array(
        1	=> '<strong>Atbilde</strong> no %1$s tēmā:',
    ),
    'NOTIFICATION_POST_APPROVED'		=> '<strong>Raksts apstiprināts</strong>:',
    'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Raksts noraidīts</strong>:',
    'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Raksta apstiprinājuma</strong> pieprasījums no %1$s:',
    'NOTIFICATION_QUOTE'				=> array(
        1	=> '<strong>%1$s </strong> citēja:',
    ),
    'NOTIFICATION_REFERENCE'			=> '"%1$s"',
    'NOTIFICATION_REASON'				=> '<em>Iemesls:</em> %1$s.',
    'NOTIFICATION_REPORT_PM'			=> '<strong>Privātas ziņas sūdzība</strong> no %1$s:',
    'NOTIFICATION_REPORT_POST'			=> '<strong>Raksta sūdzība</strong> no %1$s:',
    'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Sūdzība slēdza</strong> %1$s par:',
    'NOTIFICATION_TOPIC'				=> '<strong>Jauna tēma</strong> no %1$s:',
    'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Tēma apstiprināta</strong>:',
    'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Tēma noraidīta</strong>:',
    'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Tēmas apstiprinājuma</strong> pieprasījums no %1$s:',
    'NOTIFICATION_TYPE_NOT_EXIST'		=> 'Neeksistējošs paziņojuma tips "%s".',
    'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> 'Jaunajam lietotājam “%1$s” <strong>Nepieciešama aktivizēšana</strong>',
    // Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
    'NOTIFICATION_MANY_OTHERS'			=> 'cits',
    'NOTIFICATION_X_OTHERS'				=> array(
        2	=> '%d citi',
    ),
    'NOTIFY_ADMIN'				=> 'Lūdzu paziņot foruma administratoram vai webmāsteram.',
    'NOTIFY_ADMIN_EMAIL'		=> 'Lūdzu paziņot foruma administratoram vai webmāsteram: <a href="mailto:%1$s">%1$s</a>',
    'NO_ACCESS_ATTACHMENT'		=> 'Jums nav tiesību lai piekļūtu failam.',
    'NO_ACTION'					=> 'Nav izvēlēta darbība.',
    'NO_ADMINISTRATORS'			=> 'Administratoru nav.',
    'NO_AUTH_ADMIN'				=> 'Jums nav pieejas administratora kontroles panelim.',
    'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Jūs nevarat atkārtoti autorizēties kā cits lietotājs.',
    'NO_AUTH_OPERATION'			=> 'Jums nav nepieciešamo privilēģiju lai pabeigtu šo darbību.',
    'NO_AVATARS'				=> 'Avatāri nav pieejami',
    'NO_CONNECT_TO_SMTP_HOST'	=> 'Nevar pievienoties smtp hostam : %1$s : %2$s',
    'NO_BIRTHDAYS'				=> 'Nav dzimšanas dienu',
    'NO_EMAIL_MESSAGE'			=> 'E-mail nesatur tekstu.',
    'NO_EMAIL_RESPONSE_CODE'	=> 'Nav saņemta atbilde no mail servera.',
    'NO_EMAIL_SUBJECT'			=> 'Nav norādīta e-mail tēma.',
    'NO_FORUM'					=> 'Jūsu izvēlētais forums neeksistē.',
    'NO_FORUMS'					=> 'Šajā forumā nekā nav.',
    'NO_GROUP'					=> 'Pieprasītā lietotāju grupa neeksistē.',
    'NO_GROUP_MEMBERS'			=> 'Šai grupā nav biedru.',
    'NO_IPS_DEFINED'			=> 'Nav noteikta IP adrese vai hosta nosaukums',
    'NO_MEMBERS'				=> 'Nav atrasts neviens lietotājs, kurš atbilstu meklēšanas kritērijam.',
    'NO_MESSAGES'				=> 'Nav ziņu',
    'NO_MODE'					=> 'Nav izvēlēts veids.',
    'NO_MODERATORS'				=> 'Šai forumā nav moderatoru.',
    'NO_NEW_MESSAGES'			=> 'Nav jaunu vēstuļu',
    'NO_NEW_POSTS'				=> 'Nav jaunu ziņojumu',	// Not used anymore
    'NO_ONLINE_USERS'			=> 'Nav reģistrētu lietotāju',
    'NO_POSTS'					=> 'Nav ziņojumu',
    'NO_POSTS_TIME_FRAME'		=> 'Tēmā nav ziņu par norādīto laika posmu.',
    'NO_FEED_ENABLED'			=> 'Jaunumu kanāli šim forumam nav pieejami.',
    'NO_FEED'					=> 'Pieprasītais jaunumu kanāls nav pieejams.',
    'NO_STYLE_DATA'				=> 'Nevar iegūt stila datus',
    'NO_SUBJECT'				=> 'Nav norādīta tēma',								// Used for posts having no subject defined but displayed within management pages.
    'NO_SUCH_SEARCH_MODULE'		=> 'Norādīts neeksistējošs meklēšanas modulis.',
    'NO_SUPPORTED_AUTH_METHODS'	=> 'Neeksistējoša autorizācijas metode.',
    'NO_TOPIC'					=> 'Meklētā tēma neeksistē vai ir pārcelta.',
    'NO_TOPIC_FORUM'			=> 'Tēma vai forums vairs neeksistē.',
    'NO_TOPICS'					=> 'Šajā sadaļā nav tēmu.',
    'NO_TOPICS_TIME_FRAME'		=> 'Sadaļā nav tēmu par norādīto laika posmu.',
    'NO_UNREAD_POSTS'			=> 'Nav nelasītu ierakstu',
    'NO_UPLOAD_FORM_FOUND'		=> 'Faila ielāde ir iesākta, bet pieejamais fails nav atrasts.',
    'NO_USER'					=> 'Tāds lietotājs neeksistē.',
    'NO_USERS'					=> 'Pieprasītie lietotāji neeksistē.',
    'NO_USER_SPECIFIED'			=> 'Netika norādīts lietotāja vārds.',

    // Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
    'NUM_ATTACHMENTS'		=> array(
        1	=> '%d pielikums',
        2	=> '%d pielikumi',
    ),
    'NUM_POSTS_IN_QUEUE'		=> array(
        0			=> 'Nav ziņu rindā',		// 0
        1			=> '1 viena ziņa rindā',		// 1
        2			=> '%d ziņas rindā',		// 2+
    ),

	
	
	
    'OCCUPATION'				=> 'Nodarbošanās',
    'OFFLINE'					=> 'Bezsaistē',
    'ONLINE'					=> 'Tiešsaistē',
    'ONLINE_BUDDIES'			=> 'Tiešsaistes draugi',
    // "... :: x registered and y hidden"
    'ONLINE_USERS_TOTAL'		=> array(
        1	=> 'Šobrīd šeit ir <strong>%1$d</strong> lietotājs :: %2$s un %3$s',
        2	=> 'Šobrīd šeit ir <strong>%1$d</strong> lietotāji :: %2$s un %3$s',
    ),
    // "... :: x registered, y hidden and z guests"
    'ONLINE_USERS_TOTAL_GUESTS'	=> array(
        1	=> 'Šobrīd šeit ir <strong>%1$d</strong> lietotājs :: %2$s, %3$s un %4$s',
        2	=> 'Šobrīd šeit ir <strong>%1$d</strong> lietotāji :: %2$s, %3$s un %4$s',
    ),
    'OPTIONS'					=> 'Options',

    'PAGE_OF'				=> 'Lapa <strong>%1$d</strong> no <strong>%2$d</strong>',
    'PAGE_TITLE_NUMBER'		=> 'Lapa %s',
    'PASSWORD'				=> 'Parole',
    'PIXEL'					=> 'px',
    'PIXELS'				=> array(
        1	=> '%d pikselis',
        2	=> '%d pikseļi',
    ),
    'PLAY_QUICKTIME_FILE'	=> 'Atskaņot Quicktime failu',
    'PLEASE_WAIT'			=> 'Lūdzu uzgaidiet.',
    'PM'					=> 'PZ',
    'PM_REPORTED'			=> 'Noklikšķiniet, lai skatītu ziņojumu',
    'POSTING_MESSAGE'		=> 'Saglabājam ziņu %s',
    'POSTING_PRIVATE_MESSAGE'	=> 'Tiek veidota privātā ziņa',
    'POST'					=> 'Raksts',
    'POST_ANNOUNCEMENT'		=> 'Paziņojums',
    'POST_STICKY'			=> 'Piestiprināt',
    'POSTED'				=> 'Autors',
    'POSTED_IN_FORUM'		=> 'šajā',
    'POSTED_ON_DATE'		=> 'rakstīja',
    'POSTS'					=> 'Atbildes',
    'POSTS_UNAPPROVED'		=> 'Vismaz viens ziņojums šai tēmā nav apstiprināts.',
    'POSTS_UNAPPROVED_FORUM'=> 'Vismaz viens ziņojums šai forumā nav apstiprināts.',
    'POST_BY_AUTHOR'		=> '',
    'POST_BY_FOE'			=> '<strong>%1$s</strong>, pašlaik ir jūsu ignorēto lietotāju sarakstā.',
    'POST_DISPLAY'			=> '%1$sParādīt šo ziņu%2$s.',
    'POST_DAY'				=> '%.2f ziņojumi dienā',
    'POST_DELETED_ACTION'	=> 'Dzēstie ziņojumi:',
    'POST_DELETED'			=> 'Ieraksts dzēsts.',
    'POST_DELETED_BY'		=> '<strong>%2$s</strong> dzēsa <strong>%1$s</strong> datums %3$s.',
    'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> dzēsa <strong>%1$s</strong> datums %3$s iemesls: %4$s',
    'POST_DETAILS'			=> 'Tēmas detaļas',
    'POST_NEW_TOPIC'		=> 'Izveidot jaunu tēmu',
    'POST_PCT'				=> '%.2f%% no visiem ziņojumiem',
    'POST_PCT_ACTIVE'		=> '%.2f%% no lietotāja ziņojumiem',
    'POST_PCT_ACTIVE_OWN'	=> '%.2f%% no Jūsu ziņojumiem',
    'POST_REPLY'			=> 'Publicēt atbildi',
    'POST_REPORTED'			=> 'Spied, lai apskatītu atskaiti',
    'POST_SUBJECT'			=> 'Publicēt tēmu',
    'POST_TIME'				=> 'Publikācijas laiks',
    'POST_TOPIC'			=> 'Publicēt jaunu tēmu',
    'POST_UNAPPROVED_ACTION'	=> 'Raksti gaida apstiprinājumu:',
    'POST_UNAPPROVED'		=> 'Raksts nav apstiprināts.',
    'POWERED_BY'			=> 'Darbojas, izmantojot %s',
    'PREVIEW'				=> 'Apskatīt',
    'PREVIOUS'				=> 'Iepriekšējais',		// Used in pagination
    'PREVIOUS_STEP'			=> 'Iepriekšējais',
	'PRIVACY'				=> 'Privātums',
	'PRIVATE_MESSAGE'		=> 'Privāta Ziņa',
	'PRIVATE_MESSAGES'		=> 'Privātas Ziņas',
	'PRIVATE_MESSAGING'		=> 'Privātais ziņojumu centrs',
	'PROFILE'				=> 'Lietotāja panelis',
    'QUICK_LINKS'			=> 'Saīsnes',
    'RANK'						=> 'Rangs',
    'READING_FORUM'				=> 'Apskata tēmas %s',
    'READING_GLOBAL_ANNOUNCE'	=> 'Lasa globālo ziņojumu',
    'READING_LINK'				=> 'Pāriet uz foruma saiti %s',
    'READING_TOPIC'				=> 'Lasa tēmu %s',
    'READ_PROFILE'				=> 'Profils',
    'REASON'					=> 'Iemesls',
    'RECORD_ONLINE_USERS'		=> 'Visvairāk lietotāju bija <strong>%1$s</strong>, %2$s',
    'REDIRECT'					=> 'Pārsūtīt',
    'REDIRECTS'					=> 'Pārsūtīt',
    'REGISTER'					=> 'Reģistrēties',
    'REGISTERED_USERS'			=> ' Reģistrēti lietotāji:',
    // "... and 2 hidden users online"
    'REG_USERS_ONLINE'			=> array(
        1	=> 'Šobrīd šeit ir %1$d reģistrēti lietotāji un %2$s tīklā',
        2	=> 'Šobrīd šeit ir %1$d reģistrēti lietotāji un %2$s tīklā',
    ),
    'REG_USERS_TOTAL'			=> array(
        1	=> '%d reģistrēts',
        2	=> '%d reģistrēti',
    ),
    'REMOVE'					=> 'Dzēst',
    'REMOVE_INSTALL'			=> 'Pirms lietot konferenci, lūdzu izdzēsiet, pārdēvējiet vai pārvietojiet mapi install. Pretējā gadījumā būs pieejama tikai administrācijas sadaļa.',
    'REPLIES'					=> 'Atbildes',
    'REPLY_WITH_QUOTE'			=> 'Atbildēt citējot',
    'REPLYING_GLOBAL_ANNOUNCE'	=> 'Atbilde globālajam ziņojumam',
    'REPLYING_MESSAGE'			=> 'Atbilde uz vēstuli %s',
    'REPORT_BY'					=> 'Ziņoja',
    'REPORT_POST'				=> 'Ziņo par šo ierakstu',
    'REPORTING_POST'			=> 'Ziņo par ierakstu',
    'RESEND_ACTIVATION'			=> 'Izsūtīt vēlreiz aktivizācijas epastu',
    'RESET'						=> 'Atcelt',
    'RESTORE_PERMISSIONS'		=> 'Atjaunot tiesības',
    'RETURN_INDEX'				=> '%sAtgriezties uz satura lapu%s',
    'RETURN_FORUM'				=> '%sAtgriezties uz pēdējo apmeklēto forumu%s',
    'RETURN_PAGE'				=> '%sAtgriezties uz iepriekšējo lapu%s',
    'RETURN_TOPIC'				=> '%sAtgriezties uz iepriekšējo tēmu%s',
    'RETURN_TO'					=> 'Atgriezties uz “%s”',
    'RETURN_TO_INDEX'			=> 'Uz foruma sākumu',
    'FEED'						=> 'Kanāls',
    'FEED_NEWS'					=> 'Jaunumi',
    'FEED_TOPICS_ACTIVE'		=> 'Aktīvas tēmas',
    'FEED_TOPICS_NEW'			=> 'Jaunās Tēmas',
    
	'RULES_ATTACH_CAN'			=> 'Jūs <strong>varat</strong> pievienot failus šajā forumā',
	'RULES_ATTACH_CANNOT'		=> 'Jūs <strong>nevarat</strong> pievienot failus šajā forumā',
	'RULES_DELETE_CAN'			=> 'Jūs <strong>varat</strong> dzēst savas ziņas šaja forumā',
	'RULES_DELETE_CANNOT'		=> 'Jūs <strong>nevarat</strong> dzēst savas ziņas šaja forumā',
	'RULES_DOWNLOAD_CAN'		=> 'Jūs <strong>varat</strong> lejuplādēt pievienotos failus šajā forumā',
	'RULES_DOWNLOAD_CANNOT'		=> 'Jūs <strong>nevarat</strong> lejuplādēt pievienotos failus šajā forumā',
	'RULES_EDIT_CAN'			=> 'Jūs <strong>varat</strong> rediģēt savas ziņas šajā forumā',
	'RULES_EDIT_CANNOT'			=> 'Jūs <strong>nevarat</strong> rediģēt savas ziņas šajā forumā',
	'RULES_LOCK_CAN'			=> 'Jūs <strong>varat</strong> slēgt savas tēmas šajā forumā',
	'RULES_LOCK_CANNOT'			=> 'Jūs <strong>nevarat</strong> slēgt savas tēmas šajā forumā',
	'RULES_POST_CAN'			=> 'Jūs <strong>varat</strong> izveidot jaunas tēmas šajā forumā',
	'RULES_POST_CANNOT'			=> 'Jūs <strong>nevarat</strong> izveidot jaunas tēmas šajā forumā',
	'RULES_REPLY_CAN'			=> 'Jūs <strong>varat</strong> atbildēt uz tēmām šajā forumā',
	'RULES_REPLY_CANNOT'		=> 'Jūs <strong>nevarat</strong> atbildēt uz tēmām šajā forumā',
	'RULES_VOTE_CAN'			=> 'Jūs <strong>varat</strong> balsot aptaujās šajā forumā',
	'RULES_VOTE_CANNOT'			=> 'Jūs <strong>nevarat</strong> balsot aptaujās šajā forumā',

	
	'SEARCH'					=> 'Meklēt',
	'SEARCH_MINI'				=> 'Meklēt...',
    'SEARCH_ADV_EXPLAIN'		=> 'Apskatīt izvērstās meklēšanas parametrus',
	'SEARCH_KEYWORDS'			=> 'Meklēt pēc atslēgas vārdiem',
	'SEARCHING_FORUMS'			=> 'Meklēt forumu',
    'SEARCH_ACTIVE_TOPICS'		=> 'Aktīvas tēmas',
   
	'SEARCH_FOR'				=> 'Meklēt',
	'SEARCH_FORUM'				=> 'Meklēt šajā forumā…',
	'SEARCH_NEW'				=> 'Jaunās ziņas',
	'SEARCH_POSTS_BY'			=> 'Meklēt ziņojumus pēc autora',
	'SEARCH_SELF'				=> 'Savas ziņas',
	'SEARCH_TOPIC'				=> 'Meklēt šajā tēmā…',
	'SEARCH_UNANSWERED'			=> 'Neatbildētās ziņas',
	'SEARCH_UNREAD'				=> 'Neizlasītās ziņas',
    'SEARCH_USER_POSTS'			=> 'Meklēt lietotāja ierakstos',
    'SECONDS'					=> 'Sekundes',
    'SEE_ALL'					=> 'Skatīt visus',
	'SELECT'					=> 'Izvēlēties',
	'SELECT_ALL_CODE'			=> 'Izvēlēties visus',
	'SELECT_DESTINATION_FORUM'	=> 'Lūdzu izvēlieties saņemošo forumu',
	'SELECT_FORUM'				=> 'Izvēlēties forumu',
	'SEND_EMAIL'				=> 'E-pasts',					// Used for submit buttons
    'SEND_EMAIL_USER'			=> 'Sūtīt e-pastu uz %s',
	'SEND_PRIVATE_MESSAGE'		=> 'Sūtīt privātu ziņu',
	'SETTINGS'					=> 'Uzstādījumi',
	'SIGNATURE'					=> 'Paraksts',
   	'SKIP'						=> 'Pāriet uz saturu',
    'SKYPE'						=> 'Skype',
    'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP serveris neatbalsta autentifikāciju.',
    'SORRY_AUTH_READ'			=> 'Jums nav tiesību lasīt šo forumu.',
    'SORRY_AUTH_VIEW_ATTACH'	=> 'Jums nav tiesības lejuplādēt šo pievienoto failu.',
    'SORT_BY'					=> 'Atlasīt pēc',
    'SORT_JOINED'				=> 'Reģistrēšanās datuma',
    'SORT_LOCATION'				=> 'Atrašanās vietas',
    'SORT_RANK'					=> 'Rangs',
    'SORT_POSTS'				=> 'Ziņas',
    'SORT_TOPIC_TITLE'			=> 'Tēmas nosaukums',
   	'SORT_USERNAME'				=> 'Lietotāja vārda',
	'SPLIT_TOPIC'				=> 'Sadalīt tēmu',
	'SQL_ERROR_OCCURRED'		=> 'Notikusi SQL kļūda pie izvēles šajā lapā. Ja kļūda atkārtojas, lūgums paziņot par to %sadministratoram%s.',
	'STATISTICS'				=> 'Statistika',
   'START_WATCHING_FORUM'		=> 'Parakstīties uz forumu',
	'START_WATCHING_TOPIC'		=> 'Parakstīties uz tēmu',
	'STOP_WATCHING_FORUM'		=> 'Atrakstīties no foruma',
	'STOP_WATCHING_TOPIC'		=> 'Atrakstīties no tēmas',
	'STRING_LIST_MULTI'			=> '%1$s un %2$s',
    'STRING_LIST_SIMPLE'		=> '%1$s un %2$s',
	'SUBFORUM'					=> 'Apakšforums',
	'SUBFORUMS'					=> 'Apakšforumi',
	'SUBJECT'					=> 'Tēma',
	'SUBMIT'					=> 'Apstiprināt',
	
    'TB'				=> 'TB', // kas tas ir vispār?
    'TERMS_USE'			=> 'Lietošanas noteikumi',
	'TEST_CONNECTION'	=> 'Pārbaudīt pieslēgumu',
	'THE_TEAM'			=> 'Komanda',
    'TIB'				=> 'TiB',
    'TIME'				=> 'Laiks',
    'TIMEOUT_PROCESSING_REQ'			=> 'Pieprasījuma taimauts.',

	
	
	
    'TOO_LARGE'						=> 'Ievadītā vērtība ir pārāk liela.',
    'TOO_LARGE_MAX_RECIPIENTS'		=> 'Vērtības <strong>Maksimālais adresātu skaits vienai privātai ziņai</strong> ievadītais iestatījums ir pārāk liels.',

    'TOO_LONG'						=> 'Ievadītā vērtība ir pārāk liela.',
    'TOO_LONG_CONFIRM_CODE'			=> 'Ievadītā apstiprinājuma koda vērtība ir pārāk liela.',
	'TOO_LONG_DATEFORMAT'			=> 'Ievadītais datuma formāts ir pārāk garš.',
	'TOO_LONG_JABBER'				=> 'Ievadītais Jabber lietotāja vārds ir pārāk garš.',
    'TOO_LONG_NEW_PASSWORD'			=> 'Parole ir pārāk gara.',
  




	'TOO_LONG_PASSWORD_CONFIRM'		=> 'Norādītais paroles apstiprinājums ir pārāk garš.',
	'TOO_LONG_USER_PASSWORD'		=> 'Parole ir pārak gara.',
	'TOO_LONG_USERNAME'				=> 'Lietotājvārds ir pārāk garš.',
	'TOO_LONG_EMAIL'				=> 'E-pasta adrese ir pārāk gara.',
   	'TOO_MANY_VOTE_OPTIONS'			=> 'Jūs esat izvēlējušies pārāk daudz atbilžu variantus balsojot.',
	'TOO_SHORT'						=> 'Ievadītā vērtība ir pārāk īsa.',

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
    'TOO_SHORT_CONFIRM_CODE'		=> 'Ievadītais drošības kods ir pārāk īss.',
    'TOO_SHORT_DATEFORMAT'			=> 'Ievadītais datuma formāts ir pārāk īss.',
    'TOO_SHORT_JABBER'				=> 'Jabber konta vārds ir pārāk īss.',
    'TOO_SHORT_NEW_PASSWORD'		=> 'Norādītā parole ir pārāk īsa.',
    'TOO_SHORT_PASSWORD_CONFIRM'	=> 'Norādītais paroles apstiprinājums ir pārāk īss.',
    'TOO_SHORT_USER_PASSWORD'		=> 'Parole ir pārak īsa.',
    'TOO_SHORT_USERNAME'			=> 'Lietotājvārds ir pārāk īss.',
	'TOO_SHORT_EMAIL'				=> 'E-pasta adrese ir pārāk īsa.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'E-pasta adreses apstiprinājums ir pārāk īss.',
	'TOO_SMALL'						=> 'Ievadītā vērtība ir pārāk maza.',
    'TOO_SMALL_MAX_RECIPIENTS'		=> 'Vērtības <strong>Maksimālais adresātu skaits vienam privātam ziņojumam</strong> uzstādījums ir pārāk īss.',

    'TOPIC'				=> 'Tēma',
    'TOPICS'			=> 'Tēmas',
    'TOPICS_UNAPPROVED'	=> 'Vismaz viena tēma šajā forumā nav apstiprināta.',
    'TOPIC_ICON'		=> 'Tēmas ikona',
	
	
	
	
	
	'TOPIC_LOCKED'		=> 'Šī tēma ir slēgta, labot ziņas un rakstīt atbildes nav iespējams.',
	'TOPIC_LOCKED_SHORT'=> 'Tēma slēgta',
	'TOPIC_MOVED'		=> 'Tēma pārvietota',
	'TOPIC_REVIEW'		=> 'Tēmas apskats',
	'TOPIC_TITLE'		=> 'Tēmas nosaukums',
	'TOPIC_UNAPPROVED'	=> 'Šī tēma nav apstiprināta',
	'TOPIC_DELETED'		=> 'Tēma dzēsta.',
    'TOTAL_ATTACHMENTS'	=> 'Pievienotie faili(s)',
    'TOTAL_LOGS'		=> array(
        1	=> '%d žurnāla ieraksts',
        2	=> '%d žurnāla ieraksti',
    ),
    'TOTAL_PMS'		=> array(
        1	=> '%d privāta vēstule',
        2	=> '%d privātas vēstules',
    ),
    'TOPIC_POLL'		=> 'Šai tēmai ir aptauja',
    'TOTAL_POSTS'		=> 'Tēmas kopā',
    'TOTAL_POSTS_COUNT'	=> array(
        2	=> 'Tēmas <strong>%d</strong>',
    ),
    'TOPIC_REPORTED'	=> 'Par šo tēmu ir nosūtīta sūdzība',
    'TOTAL_TOPICS'		=> array(
        2	=> 'Tēmas <strong>%d</strong>',
    ),
    'TOTAL_USERS'		=> array(
        2	=> 'Lietotāji <strong>%d</strong>',
    ),
    'TRACKED_PHP_ERROR'	=> 'PHP kļūda: %s',
    'TWITTER'			=> 'Twitter',
    'UNABLE_GET_IMAGE_SIZE'	=> 'Nebija iespējams noteikt attēla izmērus.',
    'UNABLE_TO_DELIVER_FILE'=> 'Nevar piegādāt failu.',
    'UNKNOWN_BROWSER'		=> 'Nevar piegādāt failu',
    'UNMARK_ALL'			=> 'Noņemt visas atzīmes',
    'UNREAD_MESSAGES'		=> 'Nelasītās vēstules',
    'UNREAD_POST'			=> 'Nelasīta atbilde',
    'UNREAD_POSTS'			=> 'Nelasītas atbildes',
    'UNWATCH_FORUM_CONFIRM'		=> 'Vai esat pārliecināts, ka vēlaties atrakstīties no foruma?',
    'UNWATCH_FORUM_DETAILED'	=> 'Vai esat pārliecināts, ka vēlaties atrakstīties no foruma “%s”?',
    'UNWATCH_TOPIC_CONFIRM'		=> 'Vai esat pārliecināts, ka vēlaties atrakstīties no tēmas?',
    'UNWATCH_TOPIC_DETAILED'	=> 'Vai esat pārliecināts, ka vēlaties atrakstīties no tēmas “%s”?',
    'UNWATCHED_FORUMS'			=> 'Jūs vairs neesat parakstījies uz izvēlētajiem forumiem.',
    'UNWATCHED_TOPICS'			=> 'Jūs vairs neesat parakstījies uz izvēlētajām tēmām.',
    'UNWATCHED_FORUMS_TOPICS'	=> 'Jūs vairs neesat parakstījies uz izvēlētajiem ierakstiem.',
    'UPDATE'				=> 'Atjaunot',
	'UPLOAD_IN_PROGRESS'	=> 'Notiek faila augšuplāde.',
	'URL_REDIRECT'			=> 'Ja jūsu interneta pārlūks neatbalsta automātisko pāradresāciju, %snospiediet šo linku lai pārietu%s.',
	'USERGROUPS'			=> 'Grupas',
	'USERNAME'				=> 'Lietotājvārds',
	'USERNAMES'				=> 'Lietotājvārdi',
	'USER_AVATAR'			=> 'Lietotāja avatars',
	'USER_CANNOT_READ'		=> 'Jūs nevarat lasīt ziņojumus šai forumā.',
	'USER_POSTS'			=> array(
        1	=> '%d Ziņojumus',
        2	=> '%d Ziņojumui',
    ),
    'USERS'					=> 'Lietotāji',
    'USE_PERMISSIONS'		=> 'Izmēģināt lietotāja tiesības',






	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Diemžēl jūs nevarat izmantot šo iespēju. Iespējams, ka esat nesen reģistrējušies vai arī jums jābūt aktīvākam forumos, lai saņemtu šādas tiesības.',
    'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
    'VIEWED'					=> 'Skatīt',
    'VIEWED_COUNTS'		=> array(
        0	=> 'Vēl nav skatīts',
        1	=> 'Skatīts %d reizi',
        2	=> 'Skatīts %d reizes',
    ),
    'VIEWING_CONTACT_ADMIN'		=> 'Apskata kontakta lapu',
    'VIEWING_FAQ'				=> 'Apskata FAQ',
    'VIEWING_MEMBERS'			=> 'Apskata lietotāja detaļas',
    'VIEWING_ONLINE'			=> 'Apskata, kas pašlaik ir pieslēdzies',
    'VIEWING_MCP'				=> 'Apskata moderatora kontroles paneli',
    'VIEWING_MEMBER_PROFILE'	=> 'Apskata lietotāja kontu',
    'VIEWING_PRIVATE_MESSAGES'	=> 'Apskata privātās ziņas',
    'VIEWING_REGISTER'			=> 'Reģistrē kontu',
    'VIEWING_UCP'				=> 'Apskata lietotāja kontroles paneli',
    'VIEWS'						=> 'Apskates',
	'VIEW_BOOKMARKS'			=> 'Apskatīt grāmatzīmes',
	'VIEW_FORUM_LOGS'			=> 'Apskatīt Logus',
	'VIEW_LATEST_POST'			=> 'Apskatīt jaunāko ziņojumu',
	'VIEW_NEWEST_POST'			=> 'Pāriet pie pirmās neizlasītās ziņas',
	'VIEW_NOTES'				=> 'Apskatīt lietotāja piezīmes',
	'VIEW_ONLINE_TIMES'			=> array(
        1	=> 'pēc pēdējās %d minūtes datiem',
        2	=> 'pēc pēdējo %d minūšu datiem',
    ),
	'VIEW_TOPIC'				=> 'Apskatīt tēmu',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Paziņojums: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Globāls Paziņojums: ',
	'VIEW_TOPIC_LOCKED'			=> 'Slēgts: ',
	'VIEW_TOPIC_LOGS'			=> 'Apskatīt logus',
	'VIEW_TOPIC_MOVED'			=> 'Pārvietots: ',
	'VIEW_TOPIC_POLL'			=> 'Aptauja: ',
	'VIEW_TOPIC_STICKY'			=> 'Piestiprināta: ',
	'VISIT_WEBSITE'				=> 'Pāriet uz mājaslapu',

	'WARNINGS'			=> 'Brīdinājumi',
	'WARN_USER'			=> 'Brīdināt lietotāju',
    'WATCH_FORUM_CONFIRM'	=> 'Vai esat pārliecināts, ka vēlaties pierakstīties forumā?',
    'WATCH_FORUM_DETAILED'	=> 'Vai esat pārliecināts, ka vēlaties pierakstīties forumā “%s”?',
    'WATCH_TOPIC_CONFIRM'	=> 'Vai esat pārliecināts, ka vēlaties pierakstīties  šai tēmai?',
    'WATCH_TOPIC_DETAILED'	=> 'Vai esat pārliecināts, ka vēlaties pierakstīties  tēmai “%s”?',
	'WELCOME_SUBJECT'	=> 'Laipni lūgti %s Forumā',
	'WEBSITE'			=> 'Mājas lapa',
	'WHOIS'				=> 'Whois',
	'WHO_IS_ONLINE'		=> 'Kas ir Pieslēdzies',
    'WLM'				=> 'WLM',
    'WRONG_PASSWORD'	=> 'Jūs ievadījāt nepareizu paroli.',
    'WRONG_DATA_COLOUR'			=> 'Krāsas vērtība nav derīga.',
    'WRONG_DATA_JABBER'			=> 'Jūsu ievadītais vārds nav derīgs Jabber vārds.',
	'WRONG_DATA_LANG'			=> 'Norādīta nepareiza valoda.',
    'WRONG_DATA_POST_SD'		=> 'Nederīgs datu kārtošanas virziens',
    'WRONG_DATA_POST_SK'		=> 'Nederīgs izvēlētais datu kārtošanas virziens',
    'WRONG_DATA_TOPIC_SD'		=> 'Nederīgs izvēlētais tēmas kārtošanas virziens',
    'WRONG_DATA_TOPIC_SK'		=> 'Nederīgs izvēlētais tēmas kārtošanas virziens.',
    'WROTE'						=> 'rakstīja',

    'YAHOO'				=> 'Yahoo Messenger',
    'YOUTUBE'			=> 'YouTube',
    'YEAR'				=> 'Gads',
    'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
    'YES'				=> 'Jā',
    'YOU_LAST_VISIT'	=> 'Pēdējo reizi biji: %s',

    'datetime'			=> array(
		'TODAY'		=> 'Šodien',
		'TOMORROW'	=> 'Rīt',
		'YESTERDAY'	=> 'Vakar',
        'AGO'		=> array(
			0		=> 'mazāk par minūti atpakaļ',
			1		=> '%d minūti atpakaļ',
			2		=> '%d minūtes atpakaļ',
			60		=> '1 stundu atpakaļ',
        ),

		'Sunday'	=> 'Svētdiena',
		'Monday'	=> 'Pirmdiena',
		'Tuesday'	=> 'Otrdiena',
		'Wednesday'	=> 'Trešdiena',
		'Thursday'	=> 'Ceturtdiena',
		'Friday'	=> 'Piektdiena',
		'Saturday'	=> 'Sestdiena',


		'Sun'		=> 'Sv',
		'Mon'		=> 'Pirm',
		'Tue'		=> 'Otr',
		'Wed'		=> 'Tr',
		'Thu'		=> 'Cet',
		'Fri'		=> 'Piekt',
		'Sat'		=> 'Sest',

		'January'	=> 'Janvāris',
		'February'	=> 'Februāris',
		'March'		=> 'Marts',
		'April'		=> 'Aprīlis',
		'May'		=> 'Maijs',
		'June'		=> 'Jūnijs',
		'July'		=> 'Jūlijs',
		'August'	=> 'Augusts',
		'September' => 'Septembris',
		'October'	=> 'Oktobris',
		'November'	=> 'Novembris',
		'December'	=> 'Decembris',
		'Jan'		=> 'Jan',
		'Feb'		=> 'Feb',
		'Mar'		=> 'Mar',
		'Apr'		=> 'Apr',
		'May_short'	=> 'Mai',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'Jūn',
		'Jul'		=> 'Jūl',
		'Aug'		=> 'Aug',
		'Sep'		=> 'Sep',
		'Oct'		=> 'Okt',
		'Nov'		=> 'Nov',
		'Dec'		=> 'Dec',
	),

    // Timezones can be translated. We use this for the Etc/GMT timezones here,
    // because they are named invers to their offset.
    'timezones'		=> array(
        'UTC'					=> 'UTC',
        'UTC_OFFSET'			=> 'UTC%1$s',
        'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

        'Etc/GMT-12'	=> 'UTC+12',
        'Etc/GMT-11'	=> 'UTC+11',
        'Etc/GMT-10'	=> 'UTC+10',
        'Etc/GMT-9'		=> 'UTC+9',
        'Etc/GMT-8'		=> 'UTC+8',
        'Etc/GMT-7'		=> 'UTC+7',
        'Etc/GMT-6'		=> 'UTC+6',
        'Etc/GMT-5'		=> 'UTC+5',
        'Etc/GMT-4'		=> 'UTC+4',
        'Etc/GMT-3'		=> 'UTC+3',
        'Etc/GMT-2'		=> 'UTC+2',
        'Etc/GMT-1'		=> 'UTC+1',
        'Etc/GMT+1'		=> 'UTC-1',
        'Etc/GMT+2'		=> 'UTC-2',
        'Etc/GMT+3'		=> 'UTC-3',
        'Etc/GMT+4'		=> 'UTC-4',
        'Etc/GMT+5'		=> 'UTC-5',
        'Etc/GMT+6'		=> 'UTC-6',
        'Etc/GMT+7'		=> 'UTC-7',
        'Etc/GMT+8'		=> 'UTC-8',
        'Etc/GMT+9'		=> 'UTC-9',
        'Etc/GMT+10'	=> 'UTC-10',
        'Etc/GMT+11'	=> 'UTC-11',
        'Etc/GMT+12'	=> 'UTC-12',

        'Africa/Abidjan'	=> 'Africa/Abidjan',
        'Africa/Accra'		=> 'Africa/Accra',
        'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
        'Africa/Algiers'	=> 'Africa/Algiers',
        'Africa/Asmara'		=> 'Africa/Asmara',
        'Africa/Bamako'		=> 'Africa/Bamako',
        'Africa/Bangui'		=> 'Africa/Bangui',
        'Africa/Banjul'		=> 'Africa/Banjul',
        'Africa/Bissau'		=> 'Africa/Bissau',
        'Africa/Blantyre'	=> 'Africa/Blantyre',
        'Africa/Brazzaville'	=> 'Africa/Brazzaville',
        'Africa/Bujumbura'	=> 'Africa/Bujumbura',
        'Africa/Cairo'		=> 'Africa/Cairo',
        'Africa/Casablanca'	=> 'Africa/Casablanca',
        'Africa/Ceuta'		=> 'Africa/Ceuta',
        'Africa/Conakry'	=> 'Africa/Conakry',
        'Africa/Dakar'		=> 'Africa/Dakar',
        'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
        'Africa/Djibouti'	=> 'Africa/Djibouti',
        'Africa/Douala'		=> 'Africa/Douala',
        'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
        'Africa/Freetown'	=> 'Africa/Freetown',
        'Africa/Gaborone'	=> 'Africa/Gaborone',
        'Africa/Harare'		=> 'Africa/Harare',
        'Africa/Johannesburg'	=> 'Africa/Johannesburg',
        'Africa/Juba'		=> 'Africa/Juba',
        'Africa/Kampala'	=> 'Africa/Kampala',
        'Africa/Khartoum'	=> 'Africa/Khartoum',
        'Africa/Kigali'		=> 'Africa/Kigali',
        'Africa/Kinshasa'	=> 'Africa/Kinshasa',
        'Africa/Lagos'		=> 'Africa/Lagos',
        'Africa/Libreville'	=> 'Africa/Libreville',
        'Africa/Lome'		=> 'Africa/Lome',
        'Africa/Luanda'		=> 'Africa/Luanda',
        'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
        'Africa/Lusaka'		=> 'Africa/Lusaka',
        'Africa/Malabo'		=> 'Africa/Malabo',
        'Africa/Maputo'		=> 'Africa/Maputo',
        'Africa/Maseru'		=> 'Africa/Maseru',
        'Africa/Mbabane'	=> 'Africa/Mbabane',
        'Africa/Mogadishu'	=> 'Africa/Mogadishu',
        'Africa/Monrovia'	=> 'Africa/Monrovia',
        'Africa/Nairobi'	=> 'Africa/Nairobi',
        'Africa/Ndjamena'	=> 'Africa/Ndjamena',
        'Africa/Niamey'		=> 'Africa/Niamey',
        'Africa/Nouakchott'	=> 'Africa/Nouakchott',
        'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
        'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
        'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
        'Africa/Tripoli'	=> 'Africa/Tripoli',
        'Africa/Tunis'		=> 'Africa/Tunis',
        'Africa/Windhoek'	=> 'Africa/Windhoek',

        'America/Adak'		=> 'America/Adak',
        'America/Anchorage'	=> 'America/Anchorage',
        'America/Anguilla'	=> 'America/Anguilla',
        'America/Antigua'	=> 'America/Antigua',
        'America/Araguaina'	=> 'America/Araguaina',

        'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
        'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
        'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
        'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
        'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
        'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
        'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
        'America/Argentina/Salta'		=> 'America/Argentina/Salta',
        'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
        'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
        'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
        'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

        'America/Aruba'			=> 'America/Aruba',
        'America/Asuncion'		=> 'America/Asuncion',
        'America/Atikokan'		=> 'America/Atikokan',
        'America/Bahia'			=> 'America/Bahia',
        'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
        'America/Barbados'		=> 'America/Barbados',
        'America/Belem'			=> 'America/Belem',
        'America/Belize'		=> 'America/Belize',
        'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
        'America/Boa_Vista'		=> 'America/Boa Vista',
        'America/Bogota'		=> 'America/Bogota',
        'America/Boise'			=> 'America/Boise',
        'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
        'America/Campo_Grande'	=> 'America/Campo Grande',
        'America/Cancun'		=> 'America/Cancun',
        'America/Caracas'		=> 'America/Caracas',
        'America/Cayenne'		=> 'America/Cayenne',
        'America/Cayman'		=> 'America/Cayman',
        'America/Chicago'		=> 'America/Chicago',
        'America/Chihuahua'		=> 'America/Chihuahua',
        'America/Costa_Rica'	=> 'America/Costa Rica',
        'America/Creston'		=> 'America/Creston',
        'America/Cuiaba'		=> 'America/Cuiaba',
        'America/Curacao'		=> 'America/Curacao',
        'America/Danmarkshavn'	=> 'America/Danmarkshavn',
        'America/Dawson'		=> 'America/Dawson',
        'America/Dawson_Creek'	=> 'America/Dawson Creek',
        'America/Denver'		=> 'America/Denver',
        'America/Detroit'		=> 'America/Detroit',
        'America/Dominica'		=> 'America/Dominica',
        'America/Edmonton'		=> 'America/Edmonton',
        'America/Eirunepe'		=> 'America/Eirunepe',
        'America/El_Salvador'	=> 'America/El Salvador',
        'America/Fortaleza'		=> 'America/Fortaleza',
        'America/Glace_Bay'		=> 'America/Glace Bay',
        'America/Godthab'		=> 'America/Godthab',
        'America/Goose_Bay'		=> 'America/Goose Bay',
        'America/Grand_Turk'	=> 'America/Grand Turk',
        'America/Grenada'		=> 'America/Grenada',
        'America/Guadeloupe'	=> 'America/Guadeloupe',
        'America/Guatemala'		=> 'America/Guatemala',
        'America/Guayaquil'		=> 'America/Guayaquil',
        'America/Guyana'		=> 'America/Guyana',
        'America/Halifax'		=> 'America/Halifax',
        'America/Havana'		=> 'America/Havana',
        'America/Hermosillo'		=> 'America/Hermosillo',
        'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
        'America/Indiana/Knox'		=> 'America/Indiana/Knox',
        'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
        'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
        'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
        'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
        'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
        'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
        'America/Inuvik'		=> 'America/Inuvik',
        'America/Iqaluit'		=> 'America/Iqaluit',
        'America/Jamaica'		=> 'America/Jamaica',
        'America/Juneau'		=> 'America/Juneau',
        'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
        'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
        'America/Kralendijk'	=> 'America/Kralendijk',
        'America/La_Paz'		=> 'America/La Paz',
        'America/Lima'			=> 'America/Lima',
        'America/Los_Angeles'	=> 'America/Los Angeles',
        'America/Lower_Princes'	=> 'America/Lower Princes',
        'America/Maceio'		=> 'America/Maceio',
        'America/Managua'		=> 'America/Managua',
        'America/Manaus'		=> 'America/Manaus',
        'America/Marigot'		=> 'America/Marigot',
        'America/Martinique'	=> 'America/Martinique',
        'America/Matamoros'		=> 'America/Matamoros',
        'America/Mazatlan'		=> 'America/Mazatlan',
        'America/Menominee'		=> 'America/Menominee',
        'America/Merida'		=> 'America/Merida',
        'America/Metlakatla'	=> 'America/Metlakatla',
        'America/Mexico_City'	=> 'America/Mexico City',
        'America/Miquelon'		=> 'America/Miquelon',
        'America/Moncton'		=> 'America/Moncton',
        'America/Monterrey'		=> 'America/Monterrey',
        'America/Montevideo'	=> 'America/Montevideo',
        'America/Montreal'		=> 'America/Montreal',
        'America/Montserrat'	=> 'America/Montserrat',
        'America/Nassau'		=> 'America/Nassau',
        'America/New_York'		=> 'America/New York',
        'America/Nipigon'		=> 'America/Nipigon',
        'America/Nome'			=> 'America/Nome',
        'America/Noronha'		=> 'America/Noronha',
        'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
        'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
        'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
        'America/Ojinaga'		=> 'America/Ojinaga',
        'America/Panama'		=> 'America/Panama',
        'America/Pangnirtung'	=> 'America/Pangnirtung',
        'America/Paramaribo'	=> 'America/Paramaribo',
        'America/Phoenix'		=> 'America/Phoenix',
        'America/Port-au-Prince'	=> 'America/Port-au-Prince',
        'America/Port_of_Spain'	=> 'America/Port of Spain',
        'America/Porto_Velho'	=> 'America/Porto Velho',
        'America/Puerto_Rico'	=> 'America/Puerto Rico',
        'America/Rainy_River'	=> 'America/Rainy River',
        'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
        'America/Recife'		=> 'America/Recife',
        'America/Regina'		=> 'America/Regina',
        'America/Resolute'		=> 'America/Resolute',
        'America/Rio_Branco'	=> 'America/Rio Branco',
        'America/Santa_Isabel'	=> 'America/Santa Isabel',
        'America/Santarem'		=> 'America/Santarem',
        'America/Santiago'		=> 'America/Santiago',
        'America/Santo_Domingo'	=> 'America/Santo Domingo',
        'America/Sao_Paulo'		=> 'America/Sao Paulo',
        'America/Scoresbysund'	=> 'America/Scoresbysund',
        'America/Shiprock'		=> 'America/Shiprock',
        'America/Sitka'			=> 'America/Sitka',
        'America/St_Barthelemy'	=> 'America/St. Barthelemy',
        'America/St_Johns'		=> 'America/St. Johns',
        'America/St_Kitts'		=> 'America/St. Kitts',
        'America/St_Lucia'		=> 'America/St. Lucia',
        'America/St_Thomas'		=> 'America/St. Thomas',
        'America/St_Vincent'	=> 'America/St. Vincent',
        'America/Swift_Current'	=> 'America/Swift Current',
        'America/Tegucigalpa'	=> 'America/Tegucigalpa',
        'America/Thule'			=> 'America/Thule',
        'America/Thunder_Bay'	=> 'America/Thunder Bay',
        'America/Tijuana'		=> 'America/Tijuana',
        'America/Toronto'		=> 'America/Toronto',
        'America/Tortola'		=> 'America/Tortola',
        'America/Vancouver'		=> 'America/Vancouver',
        'America/Whitehorse'	=> 'America/Whitehorse',
        'America/Winnipeg'		=> 'America/Winnipeg',
        'America/Yakutat'		=> 'America/Yakutat',
        'America/Yellowknife'	=> 'America/Yellowknife',

        'Antarctica/Casey'		=> 'Antarctica/Casey',
        'Antarctica/Davis'		=> 'Antarctica/Davis',
        'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
        'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
        'Antarctica/Mawson'		=> 'Antarctica/Mawson',
        'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
        'Antarctica/Palmer'		=> 'Antarctica/Palmer',
        'Antarctica/Rothera'	=> 'Antarctica/Rothera',
        'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
        'Antarctica/Syowa'		=> 'Antarctica/Syowa',
        'Antarctica/Vostok'		=> 'Antarctica/Vostok',

        'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

        'Asia/Aden'			=> 'Asia/Aden',
        'Asia/Almaty'		=> 'Asia/Almaty',
        'Asia/Amman'		=> 'Asia/Amman',
        'Asia/Anadyr'		=> 'Asia/Anadyr',
        'Asia/Aqtau'		=> 'Asia/Aqtau',
        'Asia/Aqtobe'		=> 'Asia/Aqtobe',
        'Asia/Ashgabat'		=> 'Asia/Ashgabat',
        'Asia/Baghdad'		=> 'Asia/Baghdad',
        'Asia/Bahrain'		=> 'Asia/Bahrain',
        'Asia/Baku'			=> 'Asia/Baku',
        'Asia/Bangkok'		=> 'Asia/Bangkok',
        'Asia/Beirut'		=> 'Asia/Beirut',
        'Asia/Bishkek'		=> 'Asia/Bishkek',
        'Asia/Brunei'		=> 'Asia/Brunei',
        'Asia/Choibalsan'	=> 'Asia/Choibalsan',
        'Asia/Chongqing'	=> 'Asia/Chongqing',
        'Asia/Colombo'		=> 'Asia/Colombo',
        'Asia/Damascus'		=> 'Asia/Damascus',
        'Asia/Dhaka'		=> 'Asia/Dhaka',
        'Asia/Dili'			=> 'Asia/Dili',
        'Asia/Dubai'		=> 'Asia/Dubai',
        'Asia/Dushanbe'		=> 'Asia/Dushanbe',
        'Asia/Gaza'			=> 'Asia/Gaza',
        'Asia/Harbin'		=> 'Asia/Harbin',
        'Asia/Hebron'		=> 'Asia/Hebron',
        'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
        'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
        'Asia/Hovd'			=> 'Asia/Hovd',
        'Asia/Irkutsk'		=> 'Asia/Irkutsk',
        'Asia/Jakarta'		=> 'Asia/Jakarta',
        'Asia/Jayapura'		=> 'Asia/Jayapura',
        'Asia/Jerusalem'	=> 'Asia/Jerusalem',
        'Asia/Kabul'		=> 'Asia/Kabul',
        'Asia/Kamchatka'	=> 'Asia/Kamchatka',
        'Asia/Karachi'		=> 'Asia/Karachi',
        'Asia/Kashgar'		=> 'Asia/Kashgar',
        'Asia/Kathmandu'	=> 'Asia/Kathmandu',
        'Asia/Khandyga'		=> 'Asia/Khandyga',
        'Asia/Kolkata'		=> 'Asia/Kolkata',
        'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
        'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
        'Asia/Kuching'		=> 'Asia/Kuching',
        'Asia/Kuwait'		=> 'Asia/Kuwait',
        'Asia/Macau'		=> 'Asia/Macau',
        'Asia/Magadan'		=> 'Asia/Magadan',
        'Asia/Makassar'		=> 'Asia/Makassar',
        'Asia/Manila'		=> 'Asia/Manila',
        'Asia/Muscat'		=> 'Asia/Muscat',
        'Asia/Nicosia'		=> 'Asia/Nicosia',
        'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
        'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
        'Asia/Omsk'			=> 'Asia/Omsk',
        'Asia/Oral'			=> 'Asia/Oral',
        'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
        'Asia/Pontianak'	=> 'Asia/Pontianak',
        'Asia/Pyongyang'	=> 'Asia/Pyongyang',
        'Asia/Qatar'		=> 'Asia/Qatar',
        'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
        'Asia/Rangoon'		=> 'Asia/Rangoon',
        'Asia/Riyadh'		=> 'Asia/Riyadh',
        'Asia/Sakhalin'		=> 'Asia/Sakhalin',
        'Asia/Samarkand'	=> 'Asia/Samarkand',
        'Asia/Seoul'		=> 'Asia/Seoul',
        'Asia/Shanghai'		=> 'Asia/Shanghai',
        'Asia/Singapore'	=> 'Asia/Singapore',
        'Asia/Taipei'		=> 'Asia/Taipei',
        'Asia/Tashkent'		=> 'Asia/Tashkent',
        'Asia/Tbilisi'		=> 'Asia/Tbilisi',
        'Asia/Tehran'		=> 'Asia/Tehran',
        'Asia/Thimphu'		=> 'Asia/Thimphu',
        'Asia/Tokyo'		=> 'Asia/Tokyo',
        'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
        'Asia/Urumqi'		=> 'Asia/Urumqi',
        'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
        'Asia/Vientiane'	=> 'Asia/Vientiane',
        'Asia/Vladivostok'	=> 'Asia/Vladivostok',
        'Asia/Yakutsk'		=> 'Asia/Yakutsk',
        'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
        'Asia/Yerevan'		=> 'Asia/Yerevan',

        'Atlantic/Azores'		=> 'Atlantic/Azores',
        'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
        'Atlantic/Canary'		=> 'Atlantic/Canary',
        'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
        'Atlantic/Faroe'		=> 'Atlantic/Faroe',
        'Atlantic/Madeira'		=> 'Atlantic/Madeira',
        'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
        'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
        'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
        'Atlantic/Stanley'		=> 'Atlantic/Stanley',

        'Australia/Adelaide'	=> 'Australia/Adelaide',
        'Australia/Brisbane'	=> 'Australia/Brisbane',
        'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
        'Australia/Currie'		=> 'Australia/Currie',
        'Australia/Darwin'		=> 'Australia/Darwin',
        'Australia/Eucla'		=> 'Australia/Eucla',
        'Australia/Hobart'		=> 'Australia/Hobart',
        'Australia/Lindeman'	=> 'Australia/Lindeman',
        'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
        'Australia/Melbourne'	=> 'Australia/Melbourne',
        'Australia/Perth'		=> 'Australia/Perth',
        'Australia/Sydney'		=> 'Australia/Sydney',

        'Europe/Amsterdam'	=> 'Europe/Amsterdam',
        'Europe/Andorra'	=> 'Europe/Andorra',
        'Europe/Athens'		=> 'Europe/Athens',
        'Europe/Belgrade'	=> 'Europe/Belgrade',
        'Europe/Berlin'		=> 'Europe/Berlin',
        'Europe/Bratislava'	=> 'Europe/Bratislava',
        'Europe/Brussels'	=> 'Europe/Brussels',
        'Europe/Bucharest'	=> 'Europe/Bucharest',
        'Europe/Budapest'	=> 'Europe/Budapest',
        'Europe/Busingen'	=> 'Europe/Busingen',
        'Europe/Chisinau'	=> 'Europe/Chisinau',
        'Europe/Copenhagen'	=> 'Europe/Copenhagen',
        'Europe/Dublin'		=> 'Europe/Dublin',
        'Europe/Gibraltar'	=> 'Europe/Gibraltar',
        'Europe/Guernsey'	=> 'Europe/Guernsey',
        'Europe/Helsinki'	=> 'Europe/Helsinki',
        'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
        'Europe/Istanbul'	=> 'Europe/Istanbul',
        'Europe/Jersey'		=> 'Europe/Jersey',
        'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
        'Europe/Kiev'		=> 'Europe/Kiev',
        'Europe/Lisbon'		=> 'Europe/Lisbon',
        'Europe/Ljubljana'	=> 'Europe/Ljubljana',
        'Europe/London'		=> 'Europe/London',
        'Europe/Luxembourg'	=> 'Europe/Luxembourg',
        'Europe/Madrid'		=> 'Europe/Madrid',
        'Europe/Malta'		=> 'Europe/Malta',
        'Europe/Mariehamn'	=> 'Europe/Mariehamn',
        'Europe/Minsk'		=> 'Europe/Minsk',
        'Europe/Monaco'		=> 'Europe/Monaco',
        'Europe/Moscow'		=> 'Europe/Moscow',
        'Europe/Oslo'		=> 'Europe/Oslo',
        'Europe/Paris'		=> 'Europe/Paris',
        'Europe/Podgorica'	=> 'Europe/Podgorica',
        'Europe/Prague'		=> 'Europe/Prague',
        'Europe/Riga'		=> 'Europe/Riga',
        'Europe/Rome'		=> 'Europe/Rome',
        'Europe/Samara'		=> 'Europe/Samara',
        'Europe/San_Marino'	=> 'Europe/San Marino',
        'Europe/Sarajevo'	=> 'Europe/Sarajevo',
        'Europe/Simferopol'	=> 'Europe/Simferopol',
        'Europe/Skopje'		=> 'Europe/Skopje',
        'Europe/Sofia'		=> 'Europe/Sofia',
        'Europe/Stockholm'	=> 'Europe/Stockholm',
        'Europe/Tallinn'	=> 'Europe/Tallinn',
        'Europe/Tirane'		=> 'Europe/Tirane',
        'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
        'Europe/Vaduz'		=> 'Europe/Vaduz',
        'Europe/Vatican'	=> 'Europe/Vatican',
        'Europe/Vienna'		=> 'Europe/Vienna',
        'Europe/Vilnius'	=> 'Europe/Vilnius',
        'Europe/Volgograd'	=> 'Europe/Volgograd',
        'Europe/Warsaw'		=> 'Europe/Warsaw',
        'Europe/Zagreb'		=> 'Europe/Zagreb',
        'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
        'Europe/Zurich'		=> 'Europe/Zurich',

        'Indian/Antananarivo'	=> 'Indian/Antananarivo',
        'Indian/Chagos'		=> 'Indian/Chagos',
        'Indian/Christmas'	=> 'Indian/Christmas',
        'Indian/Cocos'		=> 'Indian/Cocos',
        'Indian/Comoro'		=> 'Indian/Comoro',
        'Indian/Kerguelen'	=> 'Indian/Kerguelen',
        'Indian/Mahe'		=> 'Indian/Mahe',
        'Indian/Maldives'	=> 'Indian/Maldives',
        'Indian/Mauritius'	=> 'Indian/Mauritius',
        'Indian/Mayotte'	=> 'Indian/Mayotte',
        'Indian/Reunion'	=> 'Indian/Reunion',

        'Pacific/Apia'		=> 'Pacific/Apia',
        'Pacific/Auckland'	=> 'Pacific/Auckland',
        'Pacific/Chatham'	=> 'Pacific/Chatham',
        'Pacific/Chuuk'		=> 'Pacific/Chuuk',
        'Pacific/Easter'	=> 'Pacific/Easter',
        'Pacific/Efate'		=> 'Pacific/Efate',
        'Pacific/Enderbury'	=> 'Pacific/Enderbury',
        'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
        'Pacific/Fiji'		=> 'Pacific/Fiji',
        'Pacific/Funafuti'	=> 'Pacific/Funafuti',
        'Pacific/Galapagos'	=> 'Pacific/Galapagos',
        'Pacific/Gambier'	=> 'Pacific/Gambier',
        'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
        'Pacific/Guam'		=> 'Pacific/Guam',
        'Pacific/Honolulu'	=> 'Pacific/Honolulu',
        'Pacific/Johnston'	=> 'Pacific/Johnston',
        'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
        'Pacific/Kosrae'	=> 'Pacific/Kosrae',
        'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
        'Pacific/Majuro'	=> 'Pacific/Majuro',
        'Pacific/Marquesas'	=> 'Pacific/Marquesas',
        'Pacific/Midway'	=> 'Pacific/Midway',
        'Pacific/Nauru'		=> 'Pacific/Nauru',
        'Pacific/Niue'		=> 'Pacific/Niue',
        'Pacific/Norfolk'	=> 'Pacific/Norfolk',
        'Pacific/Noumea'	=> 'Pacific/Noumea',
        'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
        'Pacific/Palau'		=> 'Pacific/Palau',
        'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
        'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
        'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
        'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
        'Pacific/Saipan'	=> 'Pacific/Saipan',
        'Pacific/Tahiti'	=> 'Pacific/Tahiti',
        'Pacific/Tarawa'	=> 'Pacific/Tarawa',
        'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
        'Pacific/Wake'		=> 'Pacific/Wake',
        'Pacific/Wallis'	=> 'Pacific/Wallis',
    ),

    // The value is only an example and will get replaced by the current time on view
    'dateformats'	=> array(
        'd M Y, H:i'			=> '01 Jan 2007, 13:37',
        'd M Y H:i'				=> '01 Jan 2007 13:37',
        'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
        'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
        'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
        '|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
        '|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
    ),

    // The default dateformat which will be used on new installs in this language
    // Translators should change this if a the usual date format is different
    'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
